platformName: Android
automationName: UiAutomator1
deviceName: emulator-5554
appActivity: .activity.WelcomeActivity
appPackage: com.lemon.lemonban
noReset: false
chromedriverExecutableDir: C:\\chromdriver


